# AUTO-GENERATED by the game to match the current build. Do NOT edit.
from __future__ import annotations

from builtins import bool as _bool, type as _type
from typing import (
    Any as _Any,
    Callable as _Callable,
    Literal as _Literal,
    TypeVar as _TypeVar,
    dataclass_transform as _dataclass_transform,
    overload as _overload,
)

_T = _TypeVar("_T")

@_overload
def field(*, default: _T, init: _bool = ..., repr: _bool = ..., compare: _bool = ..., kw_only: _bool = ...) -> _T:
    """Configure a field with a direct default. `default_factory` is mutually exclusive."""
    ...
@_overload
def field(*, default_factory: _Callable[[], _T], init: _bool = ..., repr: _bool = ..., compare: _bool = ..., kw_only: _bool = ...) -> _T:
    """Configure a field with a zero-argument factory, called once per new instance."""
    ...
@_overload
def field(*, init: _bool = ..., repr: _bool = ..., compare: _bool = ..., kw_only: _bool = ...) -> _Any:
    """Configure a required field or exclude it from generated behavior."""
    ...

@_dataclass_transform(eq_default=True, order_default=False, kw_only_default=False, field_specifiers=(field,))
@_overload
def dataclass(cls: _type[_T], /, *, init: _bool = ..., repr: _bool = ..., eq: _bool = ..., order: _bool = ..., kw_only: _bool = ..., unsafe_hash: _Literal[False] = ..., frozen: _Literal[False] = ..., slots: _Literal[False] = ..., weakref_slot: _Literal[False] = ...) -> _type[_T]:
    """Generate supported record-class methods on `cls`."""
    ...
@_overload
def dataclass(cls: None = ..., /, *, init: _bool = ..., repr: _bool = ..., eq: _bool = ..., order: _bool = ..., kw_only: _bool = ..., unsafe_hash: _Literal[False] = ..., frozen: _Literal[False] = ..., slots: _Literal[False] = ..., weakref_slot: _Literal[False] = ...) -> _Callable[[_type[_T]], _type[_T]]:
    """Return a configured record-class decorator."""
    ...
