# AUTO-GENERATED by the game to match the current build. Do NOT edit.
from __future__ import annotations

from builtins import (
    bool as _bool,
    dict as _dict,
    float as _float,
    int as _int,
    list as _list,
    property as _property,
    set as _set,
    slice as _slice,
    str as _str,
    tuple as _tuple,
)
from typing import Any
from __builtins__ import Match

def reduce(fn: Any, iterable: Any, initializer: Any = ..., /) -> Any:
    """Combine an iterable into one value by repeatedly calling pure `fn(total, item)`; callbacks cannot suspend the script or mutate game state. With no initializer, the first item becomes the initial total; empty iterables then raise. Empty-with-initializer and singleton-without-initializer perform no callback call. Also available as `from functools import reduce`."""
    ...
def total_ordering(cls: Any, /) -> Any:
    """Class decorator that preserves the class object and fills missing ordering methods from `__eq__` plus one of `__lt__`, `__le__`, `__gt__`, or `__ge__`. Explicit methods are never replaced. Applying it mutates the local class namespace."""
    ...
def wraps(wrapped: Any, /) -> Any:
    """Return a decorator that preserves the wrapped callable's supported name, qualified name, docstring, custom attributes, and `__wrapped__` link while keeping the wrapper's call behavior. Applying the returned decorator mutates only that local wrapper function."""
    ...
