# AUTO-GENERATED by the game to match the current build. Do NOT edit.
from __future__ import annotations

from builtins import (
    bool as _bool,
    dict as _dict,
    float as _float,
    int as _int,
    list as _list,
    property as _property,
    set as _set,
    slice as _slice,
    str as _str,
    tuple as _tuple,
)
from typing import Any
from __builtins__ import Match

def random() -> _float:
    """Random floating-point number `>= 0` and `< 1`. Each successful run begins a new automatic sequence. Also available as `random.random()` after `import random`."""
    ...
def rand() -> _float:
    """Short alias for `random()`: a random floating-point number `>= 0` and `< 1`. Each successful run begins a new automatic sequence. Also available as `random.rand()` after `import random`."""
    ...
def randint(min: _float, max: _float, /) -> _int:
    """Random integer `N` where `min <= N <= max`. Bounds are inclusive and must be whole numbers. Each successful run begins a new automatic sequence. Useful with `planet.get_bounds()` for random valid coordinates. Also available as `random.randint(min, max)` after `import random`."""
    ...
def seed(a: Any = ...) -> None:
    """Initialize random-number generation. Omit `a` or pass `None` to select another automatic sequence. Pass a number, boolean, or string to make later draws reproducible; the same value produces the same sequence."""
    ...
