# AUTO-GENERATED by the game to match the current build. Do NOT edit.
from __future__ import annotations

from builtins import (
    bool as _bool,
    dict as _dict,
    float as _float,
    int as _int,
    list as _list,
    property as _property,
    set as _set,
    slice as _slice,
    str as _str,
    tuple as _tuple,
)
from typing import Any
from __builtins__ import Match

# Case-insensitive matching flag. Short alias: `re.I`.
IGNORECASE: _int
# `^` and `$` also match line boundaries. Short alias: `re.M`.
MULTILINE: _int
# `.` also matches newline characters. Short alias: `re.S`.
DOTALL: _int
# Short alias for `re.IGNORECASE`.
I: _int
# Short alias for `re.MULTILINE`.
M: _int
# Short alias for `re.DOTALL`.
S: _int

def search(pattern: _str, string: _str, flags: _int = ...) -> Match | None:
    """Search anywhere in `string` for `pattern`. Returns a `Match` object, or `None` if there is no match. Patterns use the documented safe regular expression subset."""
    ...
def match(pattern: _str, string: _str, flags: _int = ...) -> Match | None:
    """Match `pattern` at the start of `string`. Returns a `Match` object, or `None` if the start does not match."""
    ...
def fullmatch(pattern: _str, string: _str, flags: _int = ...) -> Match | None:
    """Match the whole `string` against `pattern`. Returns a `Match` object, or `None` if any part is left unmatched."""
    ...
def findall(pattern: _str, string: _str, flags: _int = ...) -> _list[Any]:
    """Return all non-overlapping matches. With no capture groups, the result is a list of matched strings. With one capture group, the result is that group. With multiple capture groups, the result is tuples."""
    ...
def sub(pattern: _str, repl: _str, string: _str, count: _int = ..., flags: _int = ...) -> _str:
    """Replace matches of `pattern` in `string` with `repl`. `count=0` replaces all matches; a positive count limits replacements. Replacement text supports numeric backreferences like `\\1` and `\\g<1>`."""
    ...
def split(pattern: _str, string: _str, maxsplit: _int = ..., flags: _int = ...) -> _list[Any]:
    """Split `string` wherever `pattern` matches. `maxsplit=0` means no limit. Capturing groups are included in the output, matching Python's `re.split` behavior."""
    ...
